let hotelDetails = [
	{  
		name: 'Right Side Room with green View',
		place: 'cox',
		id: 'coxbazar1',
		guests: '4',
		bedrooms: '2',
		bed: '2',
		bathrooms: '2',
		cost: '34',
		ratting: '4.8',
		rattingNumber: '20',
		description: 'Wif Air conditioning Kitchen',
		image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
	},
	{  
		name: 'Right Side Room with green View',
		place: 'cox',
		id: 'coxbazar7',
		guests: '4',
		bedrooms: '2',
		bed: '2',
		bathrooms: '2',
		cost: '34',
		ratting: '4.8',
		rattingNumber:'Wif Air conditioning Kitchen',
		image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
	},
	{  
		name: 'Light House, full lighing view View',
		place: 'cox',
		id: 'coxbazar2',
		guests: '5',
		bedrooms: '3',
		bed: '2',
		bathrooms: '2',
		cost: '35',
		ratting: '4.5',
		rattingNumber: '13',
		description: 'Wif Air conditioning Kitchen',
		image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
	},
	{  
		name: 'Glass wall with swimming pole and chair',
		place: 'sremangal',
		id: 'coxbazar3',
		guests: '2',
		bedrooms: '1',
		bed: '1',
		bathrooms: '1',
		cost: '64',
		ratting: '4.3',
		rattingNumber: '22',
		description: 'Wif Air conditioning Kitchen',
		image: 'https://images.unsplash.com/photo-1553653924-39b70295f8da?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
	},
	{  
		name: 'Left Room with see View and swimming pool',
		place: 'sremangal',
		id: 'coxbazar4',
		guests: '6',
		bedrooms: '3',
		bed: '3',
		bathrooms: '2',
		cost: '56',
		ratting: '4.7',
		rattingNumber: '45',
		description: 'Wif Air conditioning Kitchen',
		image: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
	},
	{  
		name: 'Left Room with see View and swimming pool',
		place: 'sremangal',
		id: 'coxbazar4',
		guests: '6',
		bedrooms: '3',
		bed: '3',
		bathrooms: '2',
		cost: '56',
		ratting: '4.7',
		rattingNumber: '45',
		description: 'Wif Air conditioning Kitchen',
		image: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
	},
	{  
		name: 'Right Side Room with green View',
		place: 'sundarban',
		id: 'coxbazar7',
		guests: '4',
		bedrooms: '2',
		bed: '2',
		bathrooms: '2',
		cost: '34',
		ratting: '4.8',
		rattingNumber:'Wif Air conditioning Kitchen',
		image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
	},
	{  
		name: 'Light House, full lighing view View',
		place: 'sundarban',
		id: 'coxbazar2',
		guests: '5',
		bedrooms: '3',
		bed: '2',
		bathrooms: '2',
		cost: '35',
		ratting: '4.5',
		rattingNumber: '13',
		description: 'Wif Air conditioning Kitchen',
		image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
	},
	

]
export default hotelDetails;
